# Generated by Django 5.2.7 on 2025-10-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('funcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('f_caducidad', models.DateField()),
            ],
        ),
    ]
